### ISSUE TITLE
Way to prevent client conversation creation?

### ISSUE THREAD

**Issue by gvmatera** [layerhq/node-layer-api#1]
Based on my own research this is not possible with Layer at the moment. Are there plans to include this in the future? Basically I need a way to restrict conversation creation to my own servers via the platform API.

**Comment by nilgradisnik** [comment]
You are right, we don't support this yet.

Please contact us at support@layer.com or if you have a developer account go to https://support.layer.com/hc/en-us/requests/new, this is not the right place for Layer feature requests.
