### ISSUE TITLE
Pagination/Retrieve records from ID

### ISSUE THREAD

**Issue by jdgreenberger** [layerhq/node-layer-api#11]
Is there any plan to include support for pagination/retrieve records from_id in this library? 
https://developer.layer.com/docs/client/rest#pagination

**Comment by nilgradisnik** [comment]
Yes definitely. I already started the work, it should be released in the next version shortly.

**Comment by jdgreenberger** [comment]
Awesome, thank you!

**Comment by nilgradisnik** [comment]
@jdgreenberger I misunderstood your question. The documentation that you linked is our Client API, this is a node.js library, a wrapper for our [Platform API](https://developer.layer.com/docs/platform) which is indented to be used only on the server only.

What you might be looking for is our javascript Web SDK library that supports fetching conversations using a [Query](https://developer.layer.com/docs/websdk/integration#querying) interface.

The work that I mentioned was mostly around improving the conversation methods related to metadata.

**Comment by jdgreenberger** [comment]
Ah, didn't realize I was linking to the client library. I believe the platform API rest queries also include support for page_limit and from_id in the querystring, though. I was envisioning adding an options object to the retrieval methods (i.e. messages.getAll). Right now the page_limit just defaults to 100

**Comment by nilgradisnik** [comment]
You are right about that part. But there's is no such endpoint in our Platform API that retrieves all conversation given only an App ID. Platform API supports retrieving conversations from a user perspective i.e. `conversations.getFromUser` method and that is where a support for querystring would be useful.
I'll make sure this lands in the next release.

**Comment by nilgradisnik** [comment]
@jdgreenberger Available in the [2.0.0](https://github.com/layerhq/node-layer-api/releases/tag/2.0.0) release.

**Comment by jdgreenberger** [comment]
sweet, thanks for getting that up so quick!
