### ISSUE TITLE
Promisify this library?

### ISSUE THREAD

**Issue by freak4pc** [layerhq/node-layer-api#2]
Callbacks are a thing of the past :) 
Your library seems relatively up to date and Promises are natively supported in Node. I don't see a reason why not Promisify everything instead of using callbacks.

If I'd work on a Pull Request for this, would you be willing to merge it? Or would you be willing to work on this yourself?

Thank you
Shai

**Comment by freak4pc** [comment]
I've written this for myself for now... A similar solution could be implemented for every method.
Feel free to use :)

https://gist.github.com/freak4pc/95e7ac26f61533aebcef

**Comment by nilgradisnik** [comment]
Thanks for the feedback.
It seems like you missed the section about Promises at the end of [README](https://github.com/layerhq/node-layer-api#promises).

**Comment by freak4pc** [comment]
Thanks, I guess I did miss that :) Maybe it should be before the entire documentation since it's a pretty long document. Just an offer.

Cheers!
