### ISSUE TITLE
sendTextFromUser doesn't work with api version 2.0

### ISSUE THREAD

**Issue by sashako** [layerhq/node-layer-api#21]
payload for 2.0 expects to have `sender_id` set, while `sendTextFromUser()` takes in sender id and formats payload as following `{sender: {user_id: ID}}`. Which results in 422.

**Comment by michaelkantor** [comment]
This library is currently stuck in the Server API 1.0 world, and has not been updated to work well with 2.0.  After some discussion, and based on how stale this repository has become, we've flagged it as deprecated and no longer supported.  This update has just been pushed.  

I realize that this does not really address your needs.  What I recommend instead is that you look at the REST APIs directly and use the http request library of your choice to interact with the system.  See https://docs.layer.com/reference/server_api/introduction for details on working directly with our Server API.

Michael
