### ISSUE TITLE
Unable to resolve module https 

### ISSUE THREAD

**Issue by dmitryame** [layerhq/node-layer-api#8]
I'm unable to get layer-api going, as soon as I add example initialization code, it fails compiling in xcode with the following stacktrace:

uncaught error Error: UnableToResolveError: Unable to resolve module https from /Users/dmitry/hacks/tentags/TenTags/node_modules/layer-api/lib/request.js: Invalid directory /Users/node_modules/https
    at ResolutionRequest.js:356:15
    at tryCallOne (/Users/dmitry/hacks/tentags/TenTags/node_modules/promise/lib/core.js:37:12)
    at /Users/dmitry/hacks/tentags/TenTags/node_modules/promise/lib/core.js:123:15
    at flush (/Users/dmitry/hacks/tentags/TenTags/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)

I tried clean and reinstall all npm's dependencies, clean build etc... -- nothing seems to help.

**Comment by dmitryame** [comment]
It fails as soon as I add following line:

var LayerAPI = require('layer-api');

Please help

**Comment by dmitryame** [comment]
Perhaps I was wrong and this is not intended to be used the way I'm trying to use it. Please correct me if I'm wrong. 
So, I'm trying to use it in reactnative mobile UI code, while I'm reading it's only going to work as a serverside solution. If this is correct, my apology for the noise and feel free to close the issue. Thank you.

**Comment by nilgradisnik** [comment]
This module has been designed to work on the server side using Node.js runtime. We haven't done any testing on React Native yet, it is considered unsupported.
